
version: 2.1

jobs:
  argo-rollout-deploy:
    machine:
      image: ubuntu-2204:2023.07.2
    steps:
      - checkout
      - run:
          name: Initialize K8s
          command: sh scripts/k8s-init.sh

workflows:
  argo-rollout-wf:
    jobs:
      - argo-rollout-deploy
